fix(nx): wrong port used
nx uses 4200 by default, but our app assumed
locally port 3000, i tried to set the local
NEXTAUTH_URL to 4200, but then i remembered
github oauth url assumes port 3000 as well so
instead i modified the nx settings to use port 3000

```
[next-auth][error][client_fetch_error]
https://next-auth.js.org/errors#client_fetch_error http://localhost:3000/api/auth/providers FetchError: request to http://localhost:3000/api/auth/providers failed, reason: connect ECONNREFUSED 127.0.0.1:3000
    at ClientRequest.<anonymous> (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:314:20)
    at Socket.socketErrorListener (_http_client.js:428:9)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at SignIn (D:\projects\2020-2021uam\se\lets-watch-it-together\dist\apps\lwit\.next\server\pages\index.js:3353:13)
    at processChild (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\react-dom\cjs\react-dom-server.node.development.js:3043:14)
    at resolve (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\react-dom\cjs\react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\react-dom\cjs\react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\react-dom\cjs\react-dom-server.node.development.js:3373:29)
    at renderToString (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\react-dom\cjs\react-dom-server.node.development.js:3988:27)
    at renderPage (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next\dist\next-server\server\render.js:54:851)
    at Object.ctx.renderPage (D:\projects\2020-2021uam\se\lets-watch-it-together\dist\apps\lwit\.next\server\pages\_document.js:1329:26)
    at Function.getInitialProps (D:\projects\2020-2021uam\se\lets-watch-it-together\dist\apps\lwit\.next\server\pages\_document.js:238:19)
    at Function.module.exports../src/pages/_document.tsx.MyDocument.getInitialProps (D:\projects\2020-2021uam\se\lets-watch-it-together\dist\apps\lwit\.next\server\pages\_document.js:1340:83)
    at loadGetInitialProps (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next\dist\next-server\lib\utils.js:5:101)
    at renderToHTML (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next\dist\next-server\server\render.js:54:1142)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next\dist\next-server\server\next-server.js:107:97
    at async D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next\dist\next-server\server\next-server.js:100:142
    at async DevServer.renderToHTMLWithComponents (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next\dist\next-server\server\next-server.js:132:387)
    at async DevServer.renderToHTML (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next\dist\next-server\server\next-server.js:133:522)
    at async DevServer.renderToHTML (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next\dist\server\next-dev-server.js:34:578)
    at async DevServer.render (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next\dist\next-server\server\next-server.js:72:236)
    at async Object.fn (D:\projects\2020-2021uam\se\lets-watch-it-together\node_modules\next\dist\next-server\server\next-server.js:56:580)
 ```