fix(meetings): ts incompatible context types
```
src/pages/user/[id]/meetings/new.tsx:73:36 - error TS2345: Argument of type 'GetServerSidePropsContext<ParsedUrlQuery>' is not assignable to parameter of type '{ req: NextApiRequest; }'.
  Types of property 'req' are incompatible.
    Type 'IncomingMessage & { cookies?: { [key: string]: any; }; }' is missing the following properties from type 'NextApiRequest': query, body, env

73      const session = await getSession(context)
```